---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazooka168-member
  namespace: bazooka168
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazooka168-member
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bazooka168-member
    spec:
      imagePullSecrets:
        - name: dockerhub-registrykey
      containers:
        - name: bazooka168-app
          image: codecrafterteam/demo-web:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: bazooka168-app-env
