---
apiVersion: v1
kind: Service
metadata:
  name: bazooka168-member-service
  namespace: bazooka168
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: bazooka168-member
