---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aba444-member
  namespace: aba444
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aba444-member
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aba444-member
    spec:
#      imagePullSecrets:
#        - name: dockerhub-registrykey
      containers:
        - name: aba444-app
          image: codecrafterteam/demo-web:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: aba444-app-env
